export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const SET_LOADING = "SET_LOADING";

export const ADD_TRANSIT = "CREATE_TRANSIT";
export const REMOVE_TRANSIT = "REMOVE_TRANSIT";
export const BOOK_TRANSIT = "BOOK_TRANSIT";
export const FETCH_TRANSITS_REQUEST = "FETCH_TRANSITS_REQUEST";
export const FETCH_TRANSITS_SUCCESS = "FETCH_TRANSITS_SUCCESS";
export const FETCH_TRANSITS_FAILURE = "FETCH_TRANSITS_FAILURE";
export const ADD_TRANSIT_SUCCESS = "ADD_TRANSIT_SUCCESS";
export const ADD_TRANSIT_FAILURE = "ADD_TRANSIT_FAILURE";
