export const localGovernments = [
  "Lagos Mainland",
  "Abuja Municipal",
  "Port Harcourt",
  "Ikeja",
  "Kano Municipal",
  "Enugu North",
  "Benin City",
  "Abeokuta South",
  "Ibadan North",
  "Jos North",
  "Maiduguri",
  "Calabar Municipal",
  "Uyo",
  "Owerri Municipal",
  "Kaduna North",
  "Warri South",
  "Onitsha North",
  "Eket",
  "Osogbo",
  "Katsina",
];
